esphome:
  name: ${device_name}-${device_board}-${device_number}
  friendly_name: "${friendly_name} #${device_number}"
  comment: ${comment}
  project:
    name: ${project_author}.${device_name}-${device_board}-${device_number}
    version: ${project_version}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  ap:
    password: ${wifi_ap_password}

ota:
  platform: esphome
  password: ${ota_password}

api:
  encryption:
    key: ${api_key}

logger:

captive_portal:
